Fix linker failure on macOS (#10)
Summary:
edencommon_os needs to link to folly on macOS.[^1]

Without this, building on macOS fails[^2] with

    Undefined symbols for architecture arm64:
      "folly::get_cached_pid()", referenced from:
          facebook::eden::ProcessId::current() in ProcessId.cpp.o
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[2]: *** [eden/common/os/libedencommon_os.dylib] Error 1
    make[1]: *** [eden/common/os/CMakeFiles/edencommon_os.dir/all] Error 2

[^1]: https://github.com/facebookexperimental/edencommon/blob/518f2264f4d9feda635980d1b11242fda3767fd0/eden/common/os/ProcessId.cpp#L49-L60
[^2]: https://github.com/Homebrew/homebrew-core/actions/runs/5642189825/job/15281692111#step:3:219

Pull Request resolved: https://github.com/facebookexperimental/edencommon/pull/10

Reviewed By: xavierd

Differential Revision: D50088467

Pulled By: genevievehelsel

fbshipit-source-id: 4ac77d070437294b5f4a6ef21b11cc7e9ee7fdaa